spring:
  application:
    # nacos中注册的应用名称
    name: gateway
  cloud:
    nacos:
      discovery:
        # nacos服务地址
        server-addr: localhost:8848
        # nacos用户名
        username: nacos
        # nacos密码
        password: nacos