server:
  port: 8080 # 端口号

spring:
  profiles:
    active: dev # 激活的配置文件
  cloud:
    gateway:
      # 动态路由配置
      #      discovery:
      #        locator:
      #          enabled: true  # 开启服务发现
      #          lower-case-service-id: true # 服务名称全部小写
      # 静态路由配置
      routes:
        - id: user-service # 路由id
          uri: lb://user # 负载均衡
          predicates:
            - Path=/api/user/** # 路由匹配规则
